# Generated by Django 6.1 on 2026-08-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_email', models.EmailField(default='lucilucifer844@gmail.com', max_length=254)),
            ],
        ),
    ]
