# Generated by Django 6.1 on 2026-08-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(default='123, Travel Street,\nParadise City,\nIndia - 560001'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='info@combassholiday.com', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(default='+91 98765 43210', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='website',
            field=models.CharField(default='www.combassholiday.com', max_length=200),
        ),
    ]
