# Generated by Django 6.1 on 2026-08-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_sitesettings_address_sitesettings_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='no_of_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='no_of_persons',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
